### ISSUE TITLE
Documentation building problems

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/docs#1]
1. Some Documentation sites arent build. Those who arent linked? (http://redeclipse.net/docs/Official-Maps/)
2. Maps (which are in /maps/) arent available (e.g. http://www.redeclipse.net/docs/maps/error)

#### Offtopic:
Could we use the # (first header) as the title for docs and not the file name? Because i think its better to use for e.g. the map documentation the map file name as the markdown filename as well. Remember that some maps like Fatal Error has the name Fatal Error but the filename error. And doubled filenames couldnt exist but doubled names could.

**Comment by qreeves** [comment]
Don't add a trailing slash (`/`) to the path and make sure to use an uppercase letter as the first character (`A-Z`) as I had to fix this. I want to keep the file names intact from the wiki with a redirect once I shut down the mediawiki install, so it's best to keep the file name as the header title. eg: `Fatal_Error` ↔️  `Fatal-Error.md`.

* http://www.redeclipse.net/docs/Official-Maps
* http://www.redeclipse.net/docs/maps/Error

**Comment by IceflowRE** [comment]
Ah ok.
