### ISSUE TITLE
Beta Docs "Version 2.0" wrong file name

### ISSUE THREAD

**Issue by Y0HO** [red-eclipse/docs#2]
Issue: [http://www.redeclipse.net/docs/Home](http://www.redeclipse.net/docs/Home) -> Under Development click: [Version 2.0](http://www.redeclipse.net/docs/Information-for-v2.0)
You are asked to downlad the site because the filetype is unknown. If you downlad the file and open it, you are redirected to the right website: 
[http://www.redeclipse.net/docs/Information-for-v2-0](http://www.redeclipse.net/docs/Information-for-v2-0)
http://www.redeclipse.net/docs/Information-for-v2.0 <- The wrong file link

The Solution should be to replace v2.0 by v2-0

Btw: It would be very cool if there would be a good documentation for Development. And thank you for the game!

**Comment by IceflowRE** [comment]
Thanks for reporting :)

**Comment by IceflowRE** [comment]
If you need a bit development documentation take a look into the old documentation. Its not much but a bit.

**Comment by Y0HO** [comment]
do you mean this with the old documentation? [https://redeclipse.net/wiki/Debug](https://redeclipse.net/wiki/Debug) (where the Red eclipse logo is missing in the upper left corner)

**Comment by IceflowRE** [comment]
https://redeclipse.net/wiki/Main_Page
